[baseweek, esec, NS, Eph] = almanac();
pos=24; %POS MAKES REFERENCE TO THE POSITION IN THE EPH OF THE SATELITE WE WANT TO DRAW THE FULL TRAJECTORY
%[Longitud, Latitud, name]= computeposition (Eph,esec, pos); NOT USED HERE, USED DIRECTLY IN THE PLOT FUNCTION TO CALCULATE AND PLOT AT A TIME
%[Satelitesinfo]=computeallpositions(Eph,esec); NOT USED HERE, USED DIRECTLY IN THE PLOT FUNCTION TO CALCULATE AND PLOT AT A TIME
filename='world_110m.txt'; %NAME OF THE FILE WITH THE COORDENATES TO DRAW THE MAP
plotcompletegroundtrack(filename,Eph,esec,pos); %PLOT THE COMPLETE GROUND TRACK OF ONE SATELITE. 
plotconstellation(filename,Eph,esec); %PLOTS THE FULL CONSTELLATION OF SATELITES AND THE PREDICTION OF THEIR POSITIONS IN THE NEXT HOUR IN INTERVALS OF 5 MINUTES








